### PR TITLE
Upload landing page for rf100

### PR DESCRIPTION
**Pull request by capjamesg**
# Description

This PR includes the HTML, CSS, JS, fonts, and image assets required to load the RF 100 landing page.

The visualization page is moved to `visual.html`.

## Type of change

Please delete options that are not relevant.

-   [X] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

The landing page has been tested by various members of the Roboflow team throughout development. Open the index.html file to test the landing page.

## Any specific deployment considerations

N/A

## Docs

N/A

### CODE REVIEW

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks, it's not going to work. Please add your static files in `/static`

**Review by FrancescoSaverioZuppichini — CHANGES_REQUESTED** [review]
Comment above

You can embed my visualisation page below the main page, or add a link somewhere

**Comment by capjamesg** [comment]
Why do the static assets need to be in `static`? Is there a technical reason for that? If not, it would be easier to keep the structure as is because we'd have to change all of the Webflow paths and that opens us up to incorporating accidental issues into the project.

**Comment by FrancescoSaverioZuppichini** [comment]
Yes, that is the folder that will be used to serve them, you can ctrl+f and change them by prefixing `/static`, which IDE are you using?

**Comment by capjamesg** [comment]
@FrancescoSaverioZuppichini Please review my changes.

**Review by FrancescoSaverioZuppichini — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
